Repository modelica/fmi-standard, pull requests merged in 2018-10, with the labels that each got.

#450 Fix #432: Definition of Model Variables (ModelVariables)
  docs/2_2_common_schema.adoc
Labels: specification

#455 Fixes #393 according to the suggestion in the ticket
  docs/3_1_model_exchange_math.adoc
  docs/3_2_model_exchange_api.adoc
Labels: P: minor, bug, specification

#460 Fix #426 clarify valid calls after canceled step
  docs/4_2_co-simulation_api.adoc
Labels: bug, specification

#466 Add missing parameter name for fmi3GetBinary size
  headers/fmi3FunctionTypes.h
Labels: bug

#467 Regularize state name and function name syntax
  docs/0___preamble.adoc
  docs/2_1_common_api.adoc
  docs/3_1_model_exchange_math.adoc
  docs/3_2_model_exchange_api.adoc
  docs/3_3_model_exchange_schema.adoc
  docs/4_2_co-simulation_api.adoc
Labels: bug, documents

#468 Fix #461 clarify valid calls after canceled step
  docs/4_2_co-simulation_api.adoc
Labels: bug, specification
