Repository modelica/fmi-standard, pull requests merged in 2020-02, with the labels that each got.

#722 Adjoint derivatives
  docs/2_1_common_api.adoc
  docs/5___literature.adoc
  headers/fmi3FunctionTypes.h
  headers/fmi3Functions.h
  schema/fmi3FMUType.xsd
Labels: Berlin2020

#796 removing reserved fmi3 for FMI for PLM for fmuResourceLocation
  docs/2_1_common_api.adoc
Labels: Berlin2020, discussion

#801 Clarify stepsize and discourage usage of CS for real sampled data systems but recommend HCS or SES instead
  docs/4_1_co-simulation_math.adoc
Labels: Berlin2020

#813 Renamed Scheduled Execution Simulation to Scheduled Co-Simulation
  docs/0___preamble.adoc
  docs/2_1_common_api.adoc
  docs/4_1_co-simulation_math.adoc
  docs/4_2_co-simulation_api.adoc
  docs/4_3_co-simulation_schema.adoc
  docs/4___co-simulation.adoc
  docs/examples/pseudo_code_co_simulation_scheduled_execution_simulation.txt
  headers/fmi3FunctionTypes.h
  schema/fmi3FMUType.xsd
Labels: Berlin2020, task

#824 Rename file to remove execition from name
  docs/images/state-machine-scheduled-co-simulation.svg
Labels: Berlin2020
