Repository modelica/fmi-standard, pull requests merged in 2020-04, with the labels that each got.

#866 Remove non-existent previous attribute documentation
  docs/2_1_common_api.adoc
  docs/2_2_common_schema.adoc
  docs/3_1_model_exchange_math.adoc
  docs/4_1_basic_co-simulation_math.adoc
Labels: documents

#942 Add Whats New
  docs/1___overview.adoc
Labels: PR_needed

#904 Split of Terminals and Icons into new file
  .circleci/generate_figures.ps1
  .circleci/validate_xml.py
  docs/2_2_common_schema.adoc
  docs/2_3_fmu_distribution.adoc
  docs/images/schema/CoordinateSystem.png
  docs/images/schema/GraphicalRepresentation.png
  docs/images/schema/Icon.png
  docs/images/schema/TerminalGraphicalRepresentation.png
  docs/images/schema/Terminals.png
  docs/images/schema/fmiModelDescription.png
  docs/images/schema/fmiTerminalsAndIcons.png
  schema/fmi3ModelDescription.xsd
  schema/fmi3Terminal.xsd
  schema/fmi3TerminalsAndIcons.xsd
Labels: April2020

#891 Minimal changes to fully support clock arrays
  docs/2_1_common_api.adoc
  docs/2_2_common_schema.adoc
  docs/6_2_scheduled_co-simulation_api.adoc
  headers/fmi3FunctionTypes.h
  schema/fmi3Variable.xsd
Labels: April2020, discussion
