Repository modelica/fmi-standard, pull requests merged in 2020-05, with the labels that each got.

#964 Adding basic to BCS in overivew picture
  docs/images/fmi-types-overview.drawio
  docs/images/fmi-types-overview.svg
Labels: documents

#972 Simplify state machines
  CONTRIBUTING.adoc
  docs/1___overview.adoc
  docs/2_1_common_api.adoc
  docs/2_2_common_schema.adoc
  docs/2_3_fmu_distribution.adoc
  docs/2_4_common_co-simulation.adoc
  docs/3_2_model_exchange_api.adoc
  docs/4_1_basic_co-simulation_math.adoc
  docs/4_2_basic_co-simulation_api.adoc
  docs/4_3_basic_co-simulation_schema.adoc
  docs/5_2_hybrid_co-simulation_api.adoc
  docs/6_2_scheduled_co-simulation_api.adoc
  docs/images/state-machine-basic-co-simulation.svg
  docs/images/state-machine-co-simulation.svg
  docs/images/state-machine-hybrid-co-simulation.svg
  docs/images/state-machine-model-exchange.svg
  docs/images/state-machine-scheduled-co-simulation.svg
  docs/images/state-machines.xml
  headers/fmi3FunctionTypes.h
  headers/fmi3Functions.h
Labels: discussion

#1036 Fix XML schema mechanics around variables
  schema/fmi3Variable.xsd
Labels: bug
